### ISSUE TITLE
Videos MVP

### ISSUE THREAD

**Issue by AdamYLiang** [taeinha/VidTube#6]
**Functionality**
- [x] Require thumbnail  for uploading. Right now I can submit without having a thumbnail/video file. The error renders on the first time, but if I click `Done` again then it will error out the page. 
- [x] Disable `Done` on uploads if a file is currently being uploaded. Otherwise the user can repeatedly click and send off multiple requests. 
- [x] Route user to the video show page when they upload a video 
- [x] Clicking `Upload` button when not logged in should route you to log in page. 

**CSS**
- [x] Video titles on index should be slightly smaller 
- [x] Index page grey background should extend the whole page. Consider leaving out sidebar on the left for now. 
- [x] Video should be slightly bigger on show page to match original app. If you want to make a video index on the right then those measurements need to be slightly smaller. If you want to do video index later (for search MVP) then you can center the player on the page. 
- [x] Video show page should be slightly more towards the left of the page. 

Let me know if you have any questions about these changes!

**Comment by taeinha** [comment]
- I was able to disable the submit button onSubmit event, then it gets re-enabled on success/failure

- Users get routed to the show page of the video they successfully created

- I provided the router props to the NavBar so that if a user not logged in clicks on the add-video button, then they get routed to the login page

- As discussed, I am holding off on making further CSS changes due to resolution differences. On 1080p and my laptop's chrome resolution, it appears to look identical to youtube.

**Comment by AdamYLiang** [comment]
Good changes, we can revisit the CSS issue later on. Nice work!
